# Generated by Django 3.1.7 on 2021-06-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe7', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe7',
            name='time',
        ),
    ]
